// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApis.Model;

namespace StudentApis.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentApis.Model.StudentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RollNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentClass")
                        .HasColumnType("int");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("section")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("NA");

                    b.HasKey("Id");

                    b.ToTable("student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RollNumber = "prasanna1",
                            StudentClass = 5,
                            StudentName = "prasanna",
                            section = "A"
                        },
                        new
                        {
                            Id = 2,
                            RollNumber = "Ace2",
                            StudentClass = 5,
                            StudentName = "Ace"
                        },
                        new
                        {
                            Id = 3,
                            RollNumber = "Yuno3",
                            StudentClass = 5,
                            StudentName = "Yuno"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
